# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15zPpDIFnXMZs2CYIiXBU332LSI0KWk3D
"""

import streamlit as st
import joblib
import re
import string


# -----------------------------
# Load trained models
# -----------------------------

tfidf = joblib.load("models/tfidf_vectorizer.pkl")
logistic_model = joblib.load("models/logistic_regression.pkl")


# -----------------------------
# Text preprocessing
# -----------------------------

def clean_text(text):
    text = text.lower()

    # Remove URLs
    text = re.sub(r"http\S+|www\S+|https\S+", "", text)

    # Remove mentions
    text = re.sub(r"@\w+", "", text)

    # Remove numbers
    text = re.sub(r"\d+", "", text)

    # Remove punctuation
    text = text.translate(
        str.maketrans("", "", string.punctuation)
    )

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text


# -----------------------------
# Streamlit interface
# -----------------------------

st.set_page_config(
    page_title="Airline Sentiment Analysis",
    page_icon="✈️"
)

st.title("✈️ Airline Passenger Sentiment Analysis")

st.write(
    "Enter an airline passenger review and the machine learning "
    "model will predict its sentiment."
)


review = st.text_area(
    "Enter passenger review:",
    placeholder="Example: The flight was amazing and the staff were very helpful."
)


if st.button("Predict Sentiment"):

    if review.strip() == "":
        st.warning("Please enter a review.")

    else:
        cleaned_review = clean_text(review)

        vectorized_review = tfidf.transform(
            [cleaned_review]
        )

        prediction = logistic_model.predict(
            vectorized_review
        )[0]

        if prediction == "positive":
            st.success("😊 Positive")

        elif prediction == "negative":
            st.error("😞 Negative")

        else:
            st.info("😐 Neutral")